steps:
  - name: gcr.io/cloud-builders/gcloud
    id: decrypt-id-rsa
    args:
      - kms
      - decrypt
      - --ciphertext-file=id_rsa.enc
      - --plaintext-file=id_rsa
      - --location=global
      - --keyring=cloudbuild
      - --key=id-rsa
  - name: gcr.io/cloud-builders/gcloud
    id: decrypt-gradle-properties
    args:
      - kms
      - decrypt
      - --ciphertext-file=gradle.properties.enc
      - --plaintext-file=gradle.properties
      - --location=global
      - --keyring=cloudbuild
      - --key=gradle-properties
  - name: gradle
    id: ls-dir
    entrypoint: ls
    args:
      - -la
  - name: gcr.io/cloud-builders/git
    id: git-clone
    args:
      - clone
      #- git@github.com:[GIT-USERNAME]/[REPOSITORY]
      - git@github.com:RedPillAnalytics/gradle-analytics.git
  - name: gcr.io/cloud-builders/git
    id: git-fetch
    args:
      - fetch
      - --tags
      - --unshallow
  - name: gcr.io/cloud-builders/git
    id: git-checkout
    args:
      - checkout
      - $BRANCH_NAME
  - name: gradle
    id: gradle-release
    entrypoint: gradlew
    args:
      - --build-cache
      - -Si
      - -Panalytics.buildId=$BUILD_ID
      - release
      - -Prelease.disableChecks
      - -Prelease.localOnly
