apiVersion: v1
kind: Pod
spec:
  containers:
  - name: jnlp
    env:
    - name: CONTAINER_ENV_VAR
      value: jnlp
  - name: gradle
    image: gcr.io/rpa-devops/gradle
    command: ['dockerd --host=unix:///var/run/docker.sock --host=tcp://0.0.0.0:2375 --storage-driver=overlay']
    tty: true
    env:
    - name: GRADLE_USER_HOME
      value: .gradle
