version: 2.1

executors:
  release-build-test-publish: # declares a reusable executor
    machine: true
    working_directory: ~/workspace

jobs:
    build-test-publish:
        executor: release-build-test-publish
        steps:
            - checkout
            - restore_cache:
                keys:
                    - gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - run:
                name: Release
                command: ./gradlew release -Prelease.disableChecks -Prelease.localOnly
            - run:
                name: Build and Test
                command: ./gradlew build runAllTests
            - run:
                name: Publish
                command: ./gradlew publishPlugins githubRelease -Pgradle.publish.key=${GRADLE_KEY} -Pgradle.publish.secret=${GRADLE_SECRET}
            - save_cache:
                paths:
                    - ~/.gradle
                    - ~/.m2
                key: gradle-{{ checksum "build.gradle" }}-{{ checksum "settings.gradle" }}
            - store_artifacts:
                path: build/distributions
                destination: distributions
            - store_artifacts:
                path: build/libs
                destination: libs
            - store_test_results:
                path: build/test-results

workflows:
  version: 2
  build-test-publish:
    jobs:
      - build-test-publish
